#!/usr/bin/env ruby

#Set Requirements
require 'watir'
require 'selenium-webdriver'
require 'mail'

#Using this class to close a random "Give us feedback" pop-up
class WatirProxy
  attr_reader :subject
  def initialize(browser)
    @subject = browser
  end

  def method_missing(method, *args)
    if subject.div(:id => 'acsMainInvite').exists?
       subject.link(:title => 'No, thanks').click
    end

    subject.send(method, *args)
  end
end

#Set variables
browser = WatirProxy.new(Watir::Browser.new(:chrome))

#Key is site URL, value is check-in[0]/check-out[1] date you want to stay there
list = {'https://www.recreation.gov/camping/watchman-campground/r/campgroundDetails.do?contractCode=NRSO&parkId=70923' => ['06/21/2018', '06/23/2018'], 'https://www.recreation.gov/camping/grey-cliffs-campground/r/campgroundDetails.do?contractCode=NRSO&parkId=142142' => ['06/22/2018', '06/24/2018']}

#Browser code to loop through sites and corresponding dates and send email if it finds something
list.each do |site, date|
  browser.goto(site)
  sleep 1
  browser.text_field(:id => "arrivalDate").set(date[0])
  sleep 1
  browser.text_field(:id => "departureDate").set(date[1])
  sleep 1
  browser.button(:id => "filter").click
  sleep 1
  if
    browser.link(:class => %w(book now)).exists?
  then
    puts "I'm on to something"
message = <<MESSAGE_END
    There is availability at a campsite you are watching. The details are below:

    Site: #{site}
    Check-In: #{date[0]}
    Check-Out: #{date[1]}
MESSAGE_END

  options = { :address              => "smtp.gmail.com",
              :port                 => 587,
              :user_name            => 'your_gmail_account',
              :password             => 'your_gmail_password',
              :authentication       => 'plain',
              :enable_starttls_auto => true  }

  Mail.defaults do
    delivery_method :smtp, options
  end

  Mail.deliver do
    to 'to_email@gmail.com'
    from 'from_email@gmail.com'
    subject 'There is availability at a campsite you are watching!'
    body "#{message}"
  end
 else
    puts "No Availability"
  end
end

browser.close
